-- AlterTable
ALTER TABLE "Tracking" ADD COLUMN     "clickCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "openCount" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "open" SET DEFAULT false,
ALTER COLUMN "clicked" SET DEFAULT false;
